version: '3.8'

services:
  tago-app:
    build: .
    container_name: tago_operations
    ports:
      - "8080:80"
    restart: always

  backend:
    build: ./server
    container_name: tago_backend
    ports:
      - "3000:3000"
    volumes:
      - tago_storage_v1:/app/data
    restart: always

volumes:
  tago_storage_v1:
